# Generated by Django 5.2.3 on 2025-10-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("is_movie", models.BooleanField()),
                ("is_series", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("horror", "Horror"),
                            ("drama", "Drama"),
                            ("adventure", "Adventure"),
                            ("comedy", "Comedy"),
                            ("crime", "Crime"),
                            ("slasher", "Slasher"),
                            ("western", "Western"),
                            ("war", "War"),
                            ("mystery", "Mystery"),
                            ("romance", "Romance"),
                            ("sci-fi", "Sci-fi"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "movies",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_genre",
                        to="movies.movies",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Youtube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_channel", models.CharField(max_length=100)),
                ("source_channel_id", models.CharField(max_length=100)),
                ("video_id", models.CharField(max_length=100)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_yt",
                        to="movies.movies",
                    ),
                ),
            ],
        ),
    ]
